project:
  title: "HydroBOT demo"
  type: website
  output-dir: _output
  execute-dir: project

format:
  html:
    code-link: true

website:
  title: "HydroBOT"
  repo-url: https://github.com/MDBAuth/HydroBOT_website
  page-footer:
    left: "Website, documentation, and HydroBOT work in development. Please contact g.holt@deakin.edu.au with questions or issues. To report bugs in HydroBOT, please use its [github issues](https://github.com/MDBAuth/HydroBOT/issues)"
    center:
      - text: "License"
        href: LICENSE.md
    background: secondary
  navbar:
    backgroud: primary
    search: true
    left:
      - href: getting_started.qmd
        text: Get started
      - href: workflows/workflow_overview.qmd
        text: Workflows
      - href: controller/controller_overview.qmd
        text: Controller
      - href: aggregator/aggregation_overview.qmd
        text: Aggregator
      - href: comparer/comparer_overview.qmd
        text: Comparer
      - href: provided_data/data_overview.qmd
        text: Provided data
    right:
      - icon: github
        href: https://github.com/MDBAuth/HydroBOT_website
        aria-label: GitHub

theme:
  light: flatly
  dark: flatly
# css: styles.css
toc: true

editor: visual

profile:
  group:
    - [singlefile, fullsite]
