project:
  title: "HydroBOT demo"
  type: website
  output-dir: _output
  execute-dir: project

format:
  html:
    df-print: paged
    code-link: true # Doesn't do anything for HydroBOT without either cran or pkgdown site, but still useful for external (especially {pkgname})
    embed-resources: true

website:
  title: "HydroBOT"
  repo-url: https://github.com/MDBAuth/HydroBOT
  page-footer:
    left: "HydroBOT was developed in the [climate adaptation theme](https://www.mdba.gov.au/climate-and-river-health/murray-darling-water-and-environment-research-program/climate-adaptation) of the [Murray–Darling Water and Environment Research Program](https://www.mdba.gov.au/climate-and-river-health/murray-darling-water-and-environment-research-program), a program of the [Murray-Darling Basin Authority](https://www.mdba.gov.au/).\nWebsite, documentation, and HydroBOT in beta. Please contact g.holt@deakin.edu.au with questions or issues. To report bugs in HydroBOT, please use its [github issues](https://github.com/galenholt/HydroBOT/issues)"
    center:
      - text: "License"
        href: LICENSE.md
    background: secondary
  navbar:
    backgroud: primary
    search: true
    left:
      - href: getting_started.qmd
        text: Get started
      - href: https://galenholt.github.io/HydroBOT/reference/index.html
        text: Reference
      - href: workflows/workflow_overview.qmd
        text: Workflows
      - href: controller/controller_overview.qmd
        text: Controller
      - href: aggregator/aggregation_overview.qmd
        text: Aggregator
      - href: comparer/comparer_overview.qmd
        text: Comparer
      - href: provided_data/data_overview.qmd
        text: Provided data and Causal networks
      - href: modules/module_overview.qmd
        text: Modules
    right:
      - icon: github
        href: https://github.com/MDBAuth/HydroBOT
        aria-label: GitHub

theme:
  light: flatly
  dark: flatly
# css: styles.css
toc: true

editor: visual

profile:
  group:
    - [singlefile, fullsite]
