project:
  title: "WERP_toolkit_demo"
  type: website
  output-dir: _output
  execute-dir: project
  render:
    - "*.qmd"
    - "!TESTING_PACKAGE_INSTALL.qmd"
    - "!controller/controller_ewr_testrun_py.qmd"
    - "!scenario_creation/scenario_creation_demo_py.qmd"
    - "!full_toolkit/WERP_toolkit_params.qmd"
    - "!macquarie_gauges.qmd"
    - "!comparer/plots_embedded_temp.qmd"
    - "!comparer/plot_creation_development.qmd"

website:
  title: "Using the WERP toolkit"
  page-footer:
    left: "Website, documentation, and toolkit work in progress. Not to be distributed outside QAEL, MDBA, CSIRO"
    background: secondary
  navbar:
    backgroud: primary
    search: true
    left:
      - href: scenario_creation/scenario_creation_overview.qmd
        text: Scenario creation
      - href: causal_networks/causal_overview.qmd
        text: Causal networks
      - href: controller/controller_overview.qmd
        text: Controller
      - href: aggregator/aggregation_overview.qmd
        text: Aggregator
      - href: comparer/comparer_overview.qmd
        text: Comparer
      - href: full_toolkit/full_toolkit_overview.qmd
        text: Full toolkit
    right:
      - icon: github
        href: https://github.com/MDBAuth/WERP_toolkit_demo
        aria-label: GitHub

  sidebar:


    - title: "Background"
      contents:
        - index.qmd

        - section: "Toolkit description"
          contents:
            - href: overview/spatial_data.qmd
              text: "Spatial data with toolkit"


    - title: "Scenario creation"
      contents:
        - scenario_creation/scenario_creation_overview.qmd

        - section: "Simple"
          contents:
            - href: scenario_creation/scenario_creation_demo_R.qmd
              text: "Simple scenarios for demonstration"
            - href: scenario_creation/scenario_creation_demo_py.qmd
              text: "Python version (old)"

    - title: "Causal networks"
      contents:
        - causal_networks/causal_overview.qmd

        - section: "Creation and manipulation"
          contents:
            - href: causal_networks/causal_manipulation.qmd
              text: "Building and manipulating causal networks"

        - section: "Visualisation"
          contents:
            - href: causal_networks/causal_plots.qmd
              text: "Plotting causal networks"

    - title: "Controller"
      contents:
        - controller/controller_overview.qmd

        - section: "Simple demonstration"
          contents:
            - href: controller/controller_ewr_wrapped_R.qmd
              text: "Clean simple controller"
            - href: controller/controller_ewr_stepthrough_R.qmd
              text: "Detailed step through"
            - href: controller/controller_ewr_testrun_py.qmd
              text: "Python verion (old)"


    - title: "Aggregation"
      contents:
        - aggregator/aggregation_overview.qmd
        - aggregator/aggregation_syntax.qmd

        - section: "Simple demonstration"
          contents:
            - href: aggregator/spatial_agg.qmd
              text: "Spatial aggregation capability"
            - href: aggregator/theme_agg.qmd
              text: "Theme aggregation capability"
            - href: aggregator/theme_space_agg.qmd
              text: "Multi-axis interleaved aggregation"


    - title: "Comparer"
      contents:
        - comparer/comparer_overview.qmd

        - section: "Simple demonstration"
          contents:
            - href: comparer/hydrographs.qmd
              text: "Hydrographs and baselining"
            - href: comparer/bar_plots.qmd
              text: "Bar plots (qual x)"
            - href: comparer/line_plots.qmd
              text: "Line plots (quant x)"
            - href: comparer/maps.qmd
              text: "Maps"
            - href: comparer/causal_plots.qmd
              text: "Outcomes on causal networks"


    - title: "Full toolkit"
      contents:
        - full_toolkit/full_toolkit_overview.qmd

        - section: "Simple demonstration"
          contents:
            - href: full_toolkit/WERP_toolkit_save_steps.qmd
              text: "Run toolkit, saving steps"
            - href: full_toolkit/WERP_toolkit_in_memory.qmd
              text: "Run toolkit wholly in-memory"
            - href: full_toolkit/WERP_toolkit_params.qmd
              text: "Run toolkit from params"
            - href: Presentation/walkthrough_presentation.qmd
              text: "Walkthrough presentation"

theme:
  light: flatly
  dark: flatly
# css: styles.css
toc: true

editor: visual

