project:
  title: "HydroBOT demo"
  type: website
  output-dir: _output
  execute-dir: project

# format:
#   html:
#     embed-resources: true

website:
  title: "HydroBOT examples and detail"
  repo-url: https://github.com/MDBAuth/WERP_toolkit_demo
  page-footer:
    left: "Website, documentation, and toolkit work in development. Please contact g.holt@deakin.edu.au with questions or issues. To report bugs in the toolkit, please use its [github issues](https://github.com/MDBAuth/WERP_toolkit/issues)"
    center:
      - text: "License"
        href: LICENSE.md
    background: secondary
  navbar:
    backgroud: primary
    search: true
    left:
      - href: getting_started.qmd
        text: Get started
      - href: controller/controller_overview.qmd
        text: Controller
      - href: aggregator/aggregation_overview.qmd
        text: Aggregator
      - href: comparer/comparer_overview.qmd
        text: Comparer
      - href: full_toolkit/full_toolkit_overview.qmd
        text: Full toolkit
      - href: scenario_creation/scenario_creation_overview.qmd
        text: Scenario creation
      - href: causal_networks/causal_overview.qmd
        text: Causal networks
    right:
      - icon: github
        href: https://github.com/MDBAuth/WERP_toolkit_demo
        aria-label: GitHub

theme:
  light: flatly
  dark: flatly
# css: styles.css
toc: true

editor: visual

profile:
  group:
    - [singlefile, fullsite]
