project:
  render:
    - "*.qmd"
    - "!.*_old.*"
    - "!.*demo_paper.qmd"

format:
  html:
    df-print: paged
    code-link: true # Doesn't do anything for HydroBOT without either cran or pkgdown site, but still useful for external (especially {pkgname})
    embed-resources: true

website:

  sidebar:


    - title: "Background"
      contents:
        - index.qmd

        - section: "Provided data"
          contents:
            - href: provided_data/spatial_data.qmd
              text: "Spatial data"


    - title: "Scenario creation"
      contents:
        - provided_data/scenario_creation.qmd

    - title: "Causal networks"
      contents:
        - provided_data/causal_overview.qmd

        - section: "Creation and manipulation"
          contents:
            - href: provided_data/causal_manipulation.qmd
              text: "Building and manipulating causal networks"

        - section: "Visualisation"
          contents:
            - href: provided_data/causal_plots.qmd
              text: "Plotting causal networks"

    - title: "Controller"
      contents:
        - controller/controller_overview.qmd

        - section: "Simple demonstration"
          contents:
            - href: controller/controller_ewr_wrapped.qmd
              text: "Clean simple controller"
            - href: controller/controller_ewr_stepthrough.qmd
              text: "Detailed step through"


    - title: "Aggregation"
      contents:
        - aggregator/aggregation_overview.qmd
        - aggregator/aggregation_syntax.qmd

        - section: "Simple demonstration"
          contents:
            - href: aggregator/spatial_agg.qmd
              text: "Spatial aggregation capability"
            - href: aggregator/theme_agg.qmd
              text: "Theme aggregation capability"
            - href: aggregator/using_multi_aggregate.qmd
              text: "Multi-axis interleaved aggregation"


    - title: "Comparer"
      contents:
        - comparer/comparer_overview.qmd

        - section: "Simple demonstration"
          contents:
            - href: comparer/hydrographs.qmd
              text: "Hydrographs and baselining"
            - href: comparer/bar_plots.qmd
              text: "Bar plots (qual x)"
            - href: comparer/line_plots.qmd
              text: "Line plots (quant x)"
            - href: comparer/maps.qmd
              text: "Maps"
            - href: comparer/causal_plots.qmd
              text: "Outcomes on causal networks"
            - href: comparer/heatmap.qmd
              text: "Heatmaps"


    - title: "Workflows"
      contents:
        - workflows/workflow_overview.qmd

        - section: "Simple demonstration"
          contents:
            - href: workflows/workflow_save_steps.qmd
              text: "Saving steps"
            - href: workflows/workflow_in_memory.qmd
              text: "In-memory"
            - href: workflows/workflow_parameters.qmd
              text: "From parameters"
            - href: presentation/walkthrough_presentation.qmd
              text: "Walkthrough presentation"


