---
title: "EWR gauges"
author: "Galen Holt"
---

```{r}
library(werptoolkitr)
library(dplyr)
library(sf)
library(ggplot2)
library(paletteer)

```

# Gauges in EWR

```{r}

# Get the number of EWRs at each gauge in each catchment 
newrs <- causal_ewr$ewr2obj %>% 
  group_by(gauge) %>% 
  summarise(n_ewrs = n_distinct(ewr_code))

newrs
sum(newrs$n_ewrs)

```

That's about half what I expect-is it because I'm looking at ewrs, not timing?

```{r}
# How about the timing ewrs
newrst <- causal_ewr$ewr2obj %>% 
  mutate(ect = stringr::str_c(ewr_code, stringr::str_replace_na(ewr_code_timing))) %>% 
  group_by(gauge) %>% 
  summarise(n_ewrs = n_distinct(ect))

sum(newrst$n_ewrs)
```

Attach a catchment?

```{r}
# and match them to catchment
newrs <- newrs %>% 
  gauge2geo(bom_basin_gauges) %>% 
  st_join(sdl_units) %>% 
  filter(!is.na(SWSDLName)) 

```

```{r}
ewrhist <- newrs %>% 
  ggplot(aes(x = n_ewrs, fill = SWSDLName)) + 
  geom_histogram() +
  labs(x = 'Number EWRs', y = 'Number gauges', fill = 'SDL unit') + 
  scale_fill_paletteer_d(palette = 'ggsci::default_igv') +
  theme_werp_toolkit()
ewrhist 
```

```{r}
    # plot_outcomes(newrs,
    #               y_col = 'n_ewrs',
    #               y_lab = 'Number EWRs',
    #                       x_col = 'map',
    #                       colorgroups = NULL,
    #                       colorset = 'n_ewrs',
    #                       pal_list = list('scico::oslo'),
    #                       underlay_list = sdl_units)

ewrmap <- ggplot() +
  geom_sf(data = sdl_units, fill = 'azure', color = 'grey') +
  geom_sf(data = newrs, mapping = aes(color = n_ewrs)) +
  scale_color_paletteer_c('scico::bamako') +
  theme_werp_toolkit() +
  labs(color = 'Number\nEWRs')

ewrmap
```

```{r}
ggsave('CASE_STUDY/ewr_hist.png', ewrhist, width = 12, height = 8, units = 'cm', dpi = 300)

ggsave('CASE_STUDY/ewr_map.png', ewrmap, width = 10, height = 8, units = 'cm', dpi = 300)
```
