---
title: "Gauges in case study"
author: "Galen Holt"
format: html
editor: visual
params:
  REBUILD_DATA: FALSE
---

```{r}
#| echo: false

# params don't get seen in interactive running, so handle that.
if ("params" %in% ls()) {
  REBUILD_DATA <- params$REBUILD_DATA
} else {
  REBUILD_DATA <- FALSE
}
```

## Gauges in Macquarie

For the case study, we need a list of gauges.

```{r}
#| warning: false
#| message: false
library(werptoolkitr)
library(sf)
library(reticulate) # Not strictly necessary but allows easier referencing of objects
library(ggplot2)
```

```{r}
scenario_dir <- 'CASE_STUDY'
```

### Get the ewr gauges in a dataframe

First, what gauges are in Macquarie?

```{r}
mac_poly <- resource_plan_areas %>% 
  dplyr::filter(SWWRPANAME %in% c('Macquarie-Castlereagh'))

mac_gauges <- st_intersection(bom_basin_gauges, mac_poly)
```

Then, what gauges are in ewr?

```{python}
from py_ewr.data_inputs import get_EWR_table
ewrs, badewrs = get_EWR_table()
```

Translate to R

```{r}
ewrgauges = py$ewrs$Gauge
```

Save all the macquarie gauges for the case study and note which are in EWR

```{r}
mac_gauges <- mac_gauges %>% 
  dplyr::select(gauge, site, SWWRPANAME) %>% 
  dplyr::mutate(in_ewr = ifelse(gauge %in% ewrgauges, TRUE, FALSE)) %>% 
  cbind(st_coordinates(.)) %>% 
  dplyr::rename(lon = X, lat = Y)

if (REBUILD_DATA) {
  mac_gauges %>% 
  st_drop_geometry() %>% 
  readr::write_csv(file.path(scenario_dir, 'Macquarie_gauges.csv'))
}
```

### Plot

```{r}
ggplot() +
  geom_sf(data = mac_poly) +
  geom_sf(data = mac_gauges, mapping = aes(color = in_ewr))
```

# Gauges in EWR

```{r}

# Get the number of EWRs at each gauge in each catchment 
newrs <- causal_ewr$ewr2obj %>% 
  group_by(gauge) %>% 
  summarise(n_ewrs = n_distinct(ewr_code)) %>% 
  gauge2geo(bom_basin_gauges) %>% 
  st_join(sdl_units) %>% 
  filter(!is.na(SWSDLName)) 


```

```{r}
library(paletteer)
ewrhist <- newrs %>% 
  ggplot(aes(x = n_ewrs, fill = SWSDLName)) + 
  geom_histogram() +
  labs(x = 'Number EWRs', y = 'Number gauges', fill = 'SDL unit') + 
  scale_fill_paletteer_d(palette = 'ggsci::default_igv') +
  theme_werp_toolkit()
ewrhist 
```

```{r}
    # plot_outcomes(newrs,
    #               y_col = 'n_ewrs',
    #               y_lab = 'Number EWRs',
    #                       x_col = 'map',
    #                       colorgroups = NULL,
    #                       colorset = 'n_ewrs',
    #                       pal_list = list('scico::oslo'),
    #                       underlay_list = sdl_units)

ewrmap <- ggplot() +
  geom_sf(data = sdl_units, fill = 'azure', color = 'grey') +
  geom_sf(data = newrs, mapping = aes(color = n_ewrs)) +
  scale_color_paletteer_c('scico::bamako') +
  theme_werp_toolkit() +
  labs(color = 'Number\nEWRs')

ewrmap
```

```{r}
ggsave('CASE_STUDY/ewr_hist.png', ewrhist, width = 12, height = 8, units = 'cm', dpi = 300)

ggsave('CASE_STUDY/ewr_map.png', ewrmap, width = 10, height = 8, units = 'cm', dpi = 300)
```
