---
title: "Scenario creation"
author: "Galen Holt"
format: html
editor: visual
---

## Overview

The toolkit proper begins with hydrographs as inputs. The creation of those hydrographs, and particularly their modification to create scenarios is therefore typically a step that occurs prior to the use of the toolkit. For the demonstrations here, however, we generate some example scenarios from historical hydrographs. In a very simple case used for most of the capacity demonstration simply multiplies short hydrographs by 4 and 0.25 and puts them in a standard toolkit input format using the [simple scenario notebook](scenario_creation_demo_R.qmd). This is being transitioned to a set of scenarios that is [still simple but is more interesting](scenario_creation_more.qmd), including a range of scalings and a representation of adaptation actions.

A more complex set of scenarios designed to test the toolkit and module sensitivity and be a more complete example is created from scaling historical flows according to future runoff scenarios. This analysis is done in a [separate github repo](https://github.com/MDBAuth/toolkit-flow-scaling).
