## DOES NOT QUITE WORK YET- SEE NOTES IN DOC

# Outer directory for scenario
scenario_dir: 'scenario_example'

# Preexisting data
# Hydrographs (expected to exist already)
hydro_dir: 'scenario_example/hydro_dir'

# Generated data
# EWR outputs (will be created here in controller, read from here in aggregator)
ewr_results: 'scenario_example/module_output/ewr'
# outputs of aggregator. There may be multiple modules
# NULL doesn't save it, but holds in memory.
agg_results: 'scenario_example/aggregator_output'

# Model type
model_format: 'IQQM - NSW 10,000 years'

# Climate
climate: 'Standard - 1911 to 2018 climate categorisation'

# output and return
outputType:
  - summary
  - all

returnType: 'none'

# What to aggregate
aggType: 'summary'

# Aggregation settings
agg_groups: 'scenario'
agg_var: 'ewr_achieved'
aggReturn: FALSE
namehistory: FALSE
keepAllPolys: TRUE

