# For this demonstration, we just modify the output_parent_dir and aggregation_def

# Outer directory for scenario
output_parent_dir: 'more_scenarios'

# aggregation sequences (need to be defined in R)
aggregation_def: 'full_toolkit/params.R'

