---
title: "Controller"
author: "Galen Holt"
format: html
editor: visual
---

## Overview

HydroBOT takes hydrographs as input data and then processes it through downstream modules, performs aggregation and analyses, and produces outputs. The 'Controller' component points to that input data, and sends it off to the modules with arguments controlling how that happens. It may also determine how ongoing processing occurs.

In typical use, the controller simply points to the input data and initiates processing steps according to the user. Examples of this for [the controller alone](controller_ewr_wrapped.qmd) and [the whole toolkit](../workflows/workflow_overview.qmd) are available to illustrate this, as well as a [stepthrough](controller_ewr_stepthrough.qmd) to better understand what the controller is doing.

similar to what is shown in the [combined workflow](../workflows/workflow_overview.qmd) and implement that in an analysis repo for that particular set of analyses/scenarios.

The [workflows](../workflows/workflow_overview.qmd) illustrate various workflows and example notebooks for running HydroBOT in single files, either [in memory](../workflows/workflow_in_memory) or [saving each step and reading back in](../workflows/workflow_save_steps.qmd). It can also be run [from parameter files](../workflows/workflow_parameters.qmd). These parameter files can be generated manually, but also allow replication since HydroBOT auto-documents itself when run, saving metadata files that are fully-specified parameter files.

Within this repo there are also documents providing templates for each step separately ([controller](../controller/controller_overview.qmd) and [aggregation](../aggregator/aggregation_overview.qmd)). These files allow exploring more of the options for calling, particularly for aggregation. There are also details of provided data and examples of notebooks that are not in HydroBOT flow *per se*, but are necessary for it ([scenario creation](../provided_data/scenario_creation.qmd) and [causal_networks](../provided_data/causal_overview.qmd)).
